spring:
  datasource:
    url: jdbc:h2:mem:credit-app-db
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
  output:
    ansi:
      enabled: ALWAYS