CREATE TABLE credit (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   credit_code UUID,
   credit_value DECIMAL,
   day_first_installment date,
   number_of_installment INT,
   status INT,
   costumer_id BIGINT,
   CONSTRAINT pk_credit PRIMARY KEY (id)
);

ALTER TABLE credit ADD CONSTRAINT uc_credit_creditcode UNIQUE (credit_code);

ALTER TABLE credit ADD CONSTRAINT FK_CREDIT_ON_COSTUMER FOREIGN KEY (costumer_id) REFERENCES costumer (id);